name: dbt CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-postgres
        run: pip install dbt-postgres

      - name: Wait for PostgreSQL
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Lint dbt project
        run: |
          dbt deps --profiles-dir ./ --project-dir .
          dbt parse --profiles-dir ./ --project-dir .

      - name: Run dbt debug
        run: dbt debug --profiles-dir ./ --project-dir .

      - name: Run dbt run
        run: dbt run --profiles-dir ./ --project-dir .

      - name: Run dbt test
        run: dbt test --profiles-dir ./ --project-dir .

      - name: Generate dbt docs
        run: dbt docs generate --profiles-dir ./ --project-dir .

      - name: Upload dbt docs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dbt-docs
          path: target/
