name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres

      - name: Setup dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "clickstream_sales_project:" > ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: postgres" >> ~/.dbt/profiles.yml
          echo "      host: ${{ secrets.DBT_HOST }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.DBT_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: ${{ secrets.DBT_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      port: 5432" >> ~/.dbt/profiles.yml
          echo "      dbname: ${{ secrets.DBT_DBNAME }}" >> ~/.dbt/profiles.yml
          echo "      schema: public" >> ~/.dbt/profiles.yml

      - name: Run dbt debug
        run: dbt debug --project-dir dbt

      - name: Run dbt models
        run: dbt run --project-dir dbt

      - name: Run dbt tests
        run: dbt test --project-dir dbt
